// Package docs GENERATED BY SWAG; DO NOT EDIT
package docs

import "github.com/swaggo/swag"

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "This is a sample server.",
        "title": "Example API",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "1.0"
    },
    "host": "localhost:8080",
    "basePath": "/",
    "schemes": ["http"]
}`

func init() {
    swag.Register("swagger", &s)
}

var s = swag.Spec{
    Version:          "1.0",
    Host:             "localhost:8080",
    BasePath:         "/",
    Schemes:          []string{"http"},
    Title:            "Example API",
    Description:      "This is a sample server.",
    InfoInstanceName: "swagger",
    SwaggerTemplate:  doc,
}
